//go:build generate_monad

package main

import (
	"bytes"
	"fmt"
	"io/fs"
	"log/slog"
	"os"
	"os/exec"
	"strings"
	"text/template"

	_ "embed"
)

const (
	monadGeneratorPath = "internal/generate/generate_monad.go"
	filename           = "monad.go"

	ownerWritePermission = 0o644

	argumentsLimit = 9
	resultsLimit   = 5
)

var (
	//go:embed tmpl/apply.gotmpl
	applyRaw string
)

type Variant struct {
	N, M int
	Ctx  bool
	Err  bool
}

func main() {
	funcMap := template.FuncMap{
		"add": func(x, y int) int { return x + y },
	}
	applyTmpl := template.Must(template.New("apply").Funcs(funcMap).Parse(applyRaw))

	pkg := detectPackageName()

	var buf bytes.Buffer

	buf.WriteString("// Code generated by generate_monad.go; DO NOT EDIT.\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	buf.WriteString(fmt.Sprintf("//go:generate go run %s\n", monadGeneratorPath))
	buf.WriteString("import (\n\t\"context\"\n)\n")

	for n := 1; n <= argumentsLimit; n++ {
		for m := 0; m <= resultsLimit; m++ {
			for _, args := range []Variant{
				{n, m, false, false},
				{n, m, true, false},
				{n, m, false, true},
				{n, m, true, true},
			} {
				err := applyTmpl.Execute(&buf, args)
				if err != nil {
					panic(err)
				}
				// execTemplate(monadTmpl, "Monad", args, &buf)
			}
		}
	}

	err := os.WriteFile(filename, buf.Bytes(), fs.FileMode(ownerWritePermission))
	if err != nil {
		panic(err)
	}

	slog.Info("done")
}

// —————————————————————————————————————————————————————————————
// Templates
// —————————————————————————————————————————————————————————————

var monadTmpl = `
func Monad{{.N}}{{.Suffix}}{{.TypeArgs}}(fn func({{if .Ctx}}context.Context, {{end}}{{range $i, $n := .TypeNames}}{{$n}}{{if ne $n (index $.TypeNames | last)}}, {{end}}{{end}}) {{if .Err}}(R, error){{else}}R{{end}}) {{if .Ctx}}func(context.Context) func({{range $i, $n := .ArgNums}}Opt[T{{$n}}]{{if ne $n $.N}}, {{end}}{{end}}) {{.RetType}} {{else}}func({{range $i, $n := .ArgNums}}Opt[T{{$n}}]{{if ne $n $.N}}, {{end}}{{end}}) {{.RetType}} {{end}}{
	{{if .Ctx}}return func(ctx context.Context) func({{range $i, $n := .ArgNums}}Opt[T{{$n}}]{{if ne $n $.N}}, {{end}}{{end}}) {{.RetType}} {
		return func({{range $i, $n := .ArgNums}}a{{$n}} Opt[T{{$n}}]{{if ne $n $.N}}, {{end}}{{end}}) {{.RetType}} {
			return Apply{{.N}}{{.Suffix}}({{.CtxArg}}{{range $i, $n := .ArgNums}}a{{$n}}{{if ne $n $.N}}, {{end}}{{end}}, fn)
		}
	}
	{{else}}return func({{range $i, $n := .ArgNums}}a{{$n}} Opt[T{{$n}}]{{if ne $n $.N}}, {{end}}{{end}}) {{.RetType}} {
		return Apply{{.N}}{{.Suffix}}({{range $i, $n := .ArgNums}}a{{$n}}{{if ne $n $.N}}, {{end}}{{end}}, fn)
	}
	{{end}}
}
`

func detectPackageName() string {
	out, err := exec.Command("go", "list", "-f", "{{.Name}}").Output()
	if err != nil {
		panic(err)
	}

	return strings.TrimSpace(string(out))
}
