name: coverage

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Remove generated code
        run: rm ptr/monad.go ptr/monad_test.go opt/monad.go

      - name: Test
        run: go test -v ./...

      - name: Update coverage report
        uses: crowdriff/go-coverage-gha@v0.0.4
