name: coverage

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Test
        run: go test -v -coverprofile=coverage.out ./...

      - name: Remove generated code
        run: cat coverage.out | grep -v "monad.go" > coverage.out

      - name: Update coverage report
        uses: crowdriff/go-coverage-gha@v0.0.4
